project_id = "dfaafbwhdnoaknuxonig"

[functions.update-tracking]
verify_jwt = true

[functions.send-shipment-notification]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false

[functions.email-test]
verify_jwt = true

[functions.generate-quote]
verify_jwt = false

[functions.accept-quote]
verify_jwt = false

[functions.check-expiring-quotes]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.request-customer-access]
verify_jwt = false
