project_id = "dfaafbwhdnoaknuxonig"

[functions.record-manual-payment]
verify_jwt = true

[functions.update-tracking]
verify_jwt = true

[functions.send-shipment-notification]
verify_jwt = true

[functions.send-order-notification]
verify_jwt = true

[functions.email-test]
verify_jwt = true

[functions.generate-quote]
verify_jwt = false

[functions.accept-quote]
verify_jwt = true

[functions.check-expiring-quotes]
verify_jwt = true

[functions.renew-quote]
verify_jwt = true

[functions.send-verification-email]
verify_jwt = false

[functions.request-customer-access]
verify_jwt = true

[functions.update-ups-tracking]
verify_jwt = false

[functions.cashapp-webhook]
verify_jwt = false

[functions.create-paypal-order]
verify_jwt = false

[functions.capture-paypal-payment]
verify_jwt = false

[functions.send-invoice-email]
verify_jwt = true
