project_id = "dfaafbwhdnoaknuxonig"

[functions.update-tracking]
verify_jwt = false

[functions.send-shipment-notification]
verify_jwt = false

[functions.send-order-notification]
verify_jwt = false

[functions.email-test]
verify_jwt = false

[functions.generate-quote]
verify_jwt = false